service: cw-entity

stage: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: ${opt:region, 'ap-south-1'}

  environment: 
    STAGE: ${opt:stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem        
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:Invoke
      Resource: '*'
    - Effect: Allow
      Action: 
        - cognito-idp:*
      Resource: '*'

functions:
  getentitybyid:
    handler: handlers/getentitybyid.getentity
    events:
      - http:
          path: /{cuid}/{euid}
          method: get
          cors: true

  createentity:
    handler: handlers/createentity.createEntity
    events:
      - http:
          path: /{cu_id}/{eu_id}
          method: post
          cors: true

